---

- hosts: dns-server
  gather_facts: False
  user: root
  #user: vagrant
  #sudo: True
  gather_facts: True
  vars_files:
    - vars/database.yml
    - vars/passwords.yml
    - vars/inwxpasswd.yml
    - vars/domain.yml
  roles:
      #    - up
    - database
    - dns
    - domain
    - api

