---

- hosts: all #dns-server
  gather_facts: False
  #user: root
  user: vagrant
  sudo: True
  gather_facts: True
  vars_files:
    - vars/database.yml
    - vars/passwords.yml
  roles:
      #    - up
    - database
    - dns

